feat: Update README with code examples
tagshelfsrl/dotnet-alfred-api-wrapper pull request #8
Opened 2024-05-07 19:11 UTC by Edu-B

## Description
This pull request adds examples for file upload and authentication functionality. The new examples demonstrate how to upload files to the application and implement authentication.

## Changes 
- Add code examples for `HMAC`, `API_KEY` and `OAuth` authorization
- Add code examples for both upload methods
- Add Alfred brief description

2024-05-08 10:41 UTC, rroa requested changes
These updates are positive and moving in the right direction. However, we need to concentrate on the main tasks you carry out with Alfred and consider how a third party would use it. It's important to distinguish between uploading deferred files and uploading remote files. We have not yet described the process of uploading files (whether with deferred sessions or not), creating a job, monitoring its status, and then retrieving the results after processing.

2024-05-08 10:41 UTC, rroa commented on README.md
> +   Begin by creating an instance of the Alfred client using your preferred authentication method along with the desired environment type (Production or Staging). The following examples demonstrate ho
what are the differences between environments?

2024-05-08 10:41 UTC, rroa commented on README.md
> +Alfred is a powerful document processing platform that enables you to extract, index, and search through large document collections with ease. It offers a wide range of features, including:
This is great, but the features are not arranged in a way that clearly or accurately reflects the process you want to undertake with the library.

2024-05-08 10:41 UTC, rroa commented on README.md
> +#### Upload File from Stream
Why would you choose one or the other?

2024-05-09 18:20 UTC, ypk46 requested changes
- I think some of the texts lack cohesion; they are missing commas, periods, and the correct connectors between ideas. All of my suggestions were generated and tuned using Chat GPT using your current text as input and adding the prompt `Improve this writing by fixing any grammar mistake, making it more cohesive and clear:`. Take advantage of using generative AI to improve you writing.

- I believe the main point is still missing from the discussion. It seems unnecessary to have a File section specifically. Instead, what I think is requested is a detailed walkthrough on how to use Alfred through the library. This would include a step-by-step guide from the perspective of a user (customer) on how to process a file using Alfred. Therefore, I suggest we adopt the customer's viewpoint and clearly outline the two main scenarios:

  - Uploading one or more remote files, which would immediately trigger a job.
  - Creating a session, uploading files in a deferred or asynchronous manner, and then creating the job.

  Both scenarios aim to use Alfred to process one or more files, albeit with different considerations.

2024-05-09 18:20 UTC, ypk46 commented on README.md
> +This method allows you to upload a file from a URL or multiple URLs to Alfred. You can also specify metadata for the file during the upload process you have to take into account that this method will
```suggestion
This method enables you to upload a file from one or multiple URLs to Alfred. During the upload process, you can also specify metadata for the file. Please note that using this method will automatically trigger job processing.
```

2024-05-09 18:20 UTC, ypk46 commented on README.md
> +This method allows you to upload a file from a stream to Alfred and associate it with a session ID this method will not trigger the job processing this method is ideal for uploading files that are pa
```suggestion
This method enables you to upload a file from a stream to Alfred and associate it with a specific session ID. Unlike other methods, this one does not trigger job processing, making it ideal for uploading files that are part of a larger job.
```

2024-05-09 18:20 UTC, ypk46 commented on README.md
> +- **Scalability**: Alfred is designed to scale with your needs, whether you're processing thousands of documents a day or millions.
I don't think this section should go at the end. I believe @rroa previous comments highlighted the features (bullet point) ordering (not the order in which this section appears within the whole README.md). The features list should effectively be ordered to reflect Alfred's file's journey in order to make it easier to catch.

2024-05-10 21:36 UTC, ypk46 requested changes
This looks better, but we are still missing the querying for Job results.

2024-05-10 21:36 UTC, ypk46 commented on README.md
> +**Complete example:**
I don't think we need these `Complete example` section.

2024-05-10 21:36 UTC, ypk46 commented on README.md
> +   ```csharp
This is not even a "complete" example, is missing the actual file upload.

2024-05-13 15:18 UTC, MatehElismar requested changes

2024-05-13 15:18 UTC, MatehElismar commented on README.md
> +   For OAuth authentication, specify the method and credentials explicitly and provide the environment type (Production or Staging):
Where do I get my credentials from? By answering this question I think we cover this:

> 2. Where do I start so I can use this library that allows me to access Alfred?

2024-05-13 15:18 UTC, MatehElismar commented on README.md
> +   var jobStatus = await alfred.Job.GetAsync(uploadResult.JobId);
> 4. How do I know its done?

After this, we could add information on job stages, what are the most important stages and which one determines that the process is done.

2024-05-14 10:59 UTC, rroa approved these changes
This is an improvement over the initial commit, but it still needs more work. I previously left some observations and guidelines in the form of questions for you to follow up on. There's no need to be specific by naming a "Step by Step guide"; I believe there are more elegant ways to achieve this.

I'm considering approving this now and then revisiting it for further improvements in our next sprint.

2024-05-14 14:05 UTC, MatehElismar approved these changes

2024-05-14 14:57 UTC, ypk46 approved these changes

2024-05-14 14:58 UTC, Edu-B commented
@ypk46 thanks

2024-05-14 14:58 UTC, merged